// Generate 100 responden dengan distribusi berbeda per variabel
// Usability: skewed kanan (mean ~3.9)
// UI/UX: hampir normal (mean ~3.6)
// Speed: skewed kiri (mean ~3.1)
// Features: bimodal (mean ~3.5)
// Satisfaction: normal (mean ~3.7)

export const rawData: Record<string, number>[] = [
  // Usability: kebanyakan 4-5
  { Usability: 5, "UI/UX": 4, Speed: 3, Features: 4, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 3, Speed: 2, Features: 5, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 4, Speed: 3, Features: 4, Satisfaction: 5 },
  { Usability: 4, "UI/UX": 4, Speed: 3, Features: 3, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 3, Speed: 4, Features: 5, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 4, Speed: 2, Features: 2, Satisfaction: 3 },
  { Usability: 5, "UI/UX": 5, Speed: 3, Features: 4, Satisfaction: 5 },
  { Usability: 4, "UI/UX": 3, Speed: 3, Features: 3, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 4, Speed: 4, Features: 5, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 4, Speed: 2, Features: 4, Satisfaction: 3 },
  { Usability: 5, "UI/UX": 3, Speed: 3, Features: 2, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 4, Speed: 3, Features: 5, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 4, Speed: 2, Features: 4, Satisfaction: 5 },
  { Usability: 4, "UI/UX": 3, Speed: 4, Features: 3, Satisfaction: 3 },
  { Usability: 5, "UI/UX": 5, Speed: 3, Features: 5, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 4, Speed: 2, Features: 2, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 3, Speed: 3, Features: 4, Satisfaction: 5 },
  { Usability: 4, "UI/UX": 4, Speed: 3, Features: 5, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 4, Speed: 4, Features: 4, Satisfaction: 3 },
  { Usability: 3, "UI/UX": 3, Speed: 2, Features: 3, Satisfaction: 3 },
  { Usability: 4, "UI/UX": 4, Speed: 3, Features: 2, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 3, Speed: 2, Features: 5, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 4, Speed: 3, Features: 4, Satisfaction: 3 },
  { Usability: 5, "UI/UX": 4, Speed: 4, Features: 3, Satisfaction: 5 },
  { Usability: 4, "UI/UX": 3, Speed: 2, Features: 5, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 5, Speed: 3, Features: 2, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 4, Speed: 3, Features: 4, Satisfaction: 3 },
  { Usability: 5, "UI/UX": 3, Speed: 2, Features: 5, Satisfaction: 4 },
  { Usability: 3, "UI/UX": 4, Speed: 4, Features: 3, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 3, Speed: 2, Features: 4, Satisfaction: 3 },
  { Usability: 5, "UI/UX": 4, Speed: 3, Features: 5, Satisfaction: 5 },
  { Usability: 4, "UI/UX": 4, Speed: 3, Features: 2, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 3, Speed: 4, Features: 4, Satisfaction: 3 },
  { Usability: 4, "UI/UX": 5, Speed: 2, Features: 5, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 4, Speed: 3, Features: 3, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 3, Speed: 3, Features: 4, Satisfaction: 3 },
  { Usability: 5, "UI/UX": 4, Speed: 2, Features: 5, Satisfaction: 5 },
  { Usability: 3, "UI/UX": 3, Speed: 4, Features: 2, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 4, Speed: 2, Features: 4, Satisfaction: 3 },
  { Usability: 5, "UI/UX": 4, Speed: 3, Features: 5, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 3, Speed: 3, Features: 3, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 5, Speed: 4, Features: 4, Satisfaction: 5 },
  { Usability: 4, "UI/UX": 4, Speed: 2, Features: 5, Satisfaction: 3 },
  { Usability: 5, "UI/UX": 3, Speed: 3, Features: 2, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 4, Speed: 2, Features: 4, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 4, Speed: 4, Features: 5, Satisfaction: 3 },
  { Usability: 3, "UI/UX": 3, Speed: 2, Features: 3, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 4, Speed: 3, Features: 4, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 3, Speed: 3, Features: 5, Satisfaction: 3 },
  { Usability: 4, "UI/UX": 5, Speed: 2, Features: 2, Satisfaction: 5 },
  { Usability: 5, "UI/UX": 4, Speed: 4, Features: 4, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 3, Speed: 2, Features: 5, Satisfaction: 3 },
  { Usability: 5, "UI/UX": 4, Speed: 3, Features: 3, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 4, Speed: 3, Features: 4, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 3, Speed: 2, Features: 5, Satisfaction: 3 },
  { Usability: 3, "UI/UX": 4, Speed: 4, Features: 2, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 3, Speed: 2, Features: 4, Satisfaction: 3 },
  { Usability: 5, "UI/UX": 5, Speed: 3, Features: 5, Satisfaction: 5 },
  { Usability: 4, "UI/UX": 4, Speed: 3, Features: 3, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 3, Speed: 4, Features: 4, Satisfaction: 3 },
  { Usability: 4, "UI/UX": 4, Speed: 2, Features: 5, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 4, Speed: 3, Features: 2, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 3, Speed: 2, Features: 4, Satisfaction: 3 },
  { Usability: 5, "UI/UX": 4, Speed: 4, Features: 5, Satisfaction: 5 },
  { Usability: 3, "UI/UX": 3, Speed: 2, Features: 3, Satisfaction: 3 },
  { Usability: 4, "UI/UX": 4, Speed: 3, Features: 4, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 4, Speed: 3, Features: 5, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 3, Speed: 2, Features: 2, Satisfaction: 3 },
  { Usability: 5, "UI/UX": 5, Speed: 4, Features: 4, Satisfaction: 5 },
  { Usability: 4, "UI/UX": 4, Speed: 2, Features: 5, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 3, Speed: 3, Features: 3, Satisfaction: 3 },
  { Usability: 4, "UI/UX": 4, Speed: 3, Features: 4, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 4, Speed: 2, Features: 5, Satisfaction: 4 },
  { Usability: 3, "UI/UX": 3, Speed: 4, Features: 2, Satisfaction: 3 },
  { Usability: 4, "UI/UX": 4, Speed: 2, Features: 4, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 3, Speed: 3, Features: 5, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 5, Speed: 3, Features: 3, Satisfaction: 5 },
  { Usability: 5, "UI/UX": 4, Speed: 4, Features: 4, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 3, Speed: 2, Features: 5, Satisfaction: 3 },
  { Usability: 5, "UI/UX": 4, Speed: 3, Features: 2, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 4, Speed: 2, Features: 4, Satisfaction: 3 },
  { Usability: 5, "UI/UX": 3, Speed: 4, Features: 5, Satisfaction: 4 },
  { Usability: 3, "UI/UX": 4, Speed: 2, Features: 3, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 3, Speed: 3, Features: 4, Satisfaction: 3 },
  { Usability: 5, "UI/UX": 5, Speed: 3, Features: 5, Satisfaction: 5 },
  { Usability: 4, "UI/UX": 4, Speed: 2, Features: 2, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 3, Speed: 4, Features: 4, Satisfaction: 3 },
  { Usability: 4, "UI/UX": 4, Speed: 2, Features: 5, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 4, Speed: 3, Features: 3, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 3, Speed: 3, Features: 4, Satisfaction: 3 },
  { Usability: 5, "UI/UX": 4, Speed: 2, Features: 5, Satisfaction: 5 },
  { Usability: 3, "UI/UX": 3, Speed: 4, Features: 2, Satisfaction: 3 },
  { Usability: 4, "UI/UX": 5, Speed: 2, Features: 4, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 4, Speed: 3, Features: 5, Satisfaction: 4 },
  { Usability: 4, "UI/UX": 3, Speed: 3, Features: 3, Satisfaction: 3 },
  { Usability: 5, "UI/UX": 4, Speed: 4, Features: 4, Satisfaction: 5 },
  { Usability: 4, "UI/UX": 4, Speed: 2, Features: 5, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 3, Speed: 3, Features: 2, Satisfaction: 3 },
  { Usability: 4, "UI/UX": 4, Speed: 2, Features: 4, Satisfaction: 4 },
  { Usability: 5, "UI/UX": 4, Speed: 4, Features: 5, Satisfaction: 4 },
];

export const VARIABLES = [
  "Usability",
  "UI/UX",
  "Speed",
  "Features",
  "Satisfaction",
] as const;
export type VariableName = (typeof VARIABLES)[number];
